name: Update Index

on:
  push:
    paths:
      - 'tools/**'
  workflow_dispatch: # 手动触发

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 拉取仓库
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # 保证有写权限
          fetch-depth: 0
          ref: main                 # 指定主分支

      # 2️⃣ 安装 Python（如果需要）
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 3️⃣ 生成首页 index.html
      - name: Generate index.html
        run: python3 .github/scripts/generate_index.py

      # 4️⃣ 提交并推送更改
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          # 只有 index.html 有变化才提交
          git diff-index --quiet HEAD || git commit -m "Update index.html [skip ci]"
          git push origin HEAD:main
